name: bs_test
channels:
  - conda-forge
  - anaconda
dependencies:
  - python==3.10.5
  - ipykernel==6.13.1
  - pip==22.1.2
  - autopep8==1.6.0
  - flake8==4.0.1
  - beautifulsoup4==4.11.1
  - openpyxl==3.0.9
  - pandas==1.4.2
  - requests==2.27.1