name: bs
channels:
  - conda-forge
  - anaconda
dependencies:
  - python==3.8.13
  - ipykernel==6.13.1
  - pip==22.0.4
  - autopep8==1.6.0
  - flake8==4.0.1
  - beautifulsoup4==4.11.1
  - openpyxl==3.0.9